stages:

- stage: ProvisionEnvironment
  variables:
    - group: 'Terraform Service Principal'
    - group: 'Terraform State'
    - name: tfstate_key
      value: 'jimpaine.keda-demor.master.tfstate'
    - name: resource_name
      value: 'keda'

  jobs:
  - job: TransformConfiguration
    pool:      
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in **/*.tfvars'

      inputs:
        rootDirectory: ./env
        targetFiles: '**/*.tfvars'
  
    - script: |
        terraform init \
          -backend-config="resource_group_name=$(tfstate_resource_group)" \
          -backend-config="storage_account_name=$(tfstate_storage_account)" \
          -backend-config="container_name=$(tfstate_container)" \
          -backend-config="key=$(tfstate_key)" \
          -backend-config="access_key=$(tfstate_access_key)"

      workingDirectory: ./env
      displayName: 'Terraform init'

    - script: |
       terraform apply -auto-approve

      workingDirectory: ./env
      displayName: 'Terraform apply'